### ISSUE TITLE
Saved Credentials stores multiple credentials of the same login

### ISSUE THREAD

**Issue by vanditaruldas** [didclab/onedatashare#15]
In the saved credentials screen, there is row for everytime a user login's even if he is using the same credentials. The saved credentials screen should store and display only unique logins. UserID can be shown to differentiate between logins for the same protocol.

**Comment by sraviku2** [comment]
Task completed by Javier Falca and assigned to Dhruva Kumar for code review.

**Comment by jafalca** [comment]
DOCUMENTATION

Changes:

On OAuthHandler.java starting at line 57, added a for each loop to check all existing credentials, if it matches the credential ID, then it will get rid of it.   Afterwards it will add the credential, ensuring that no repeats appear.

On StorkCred.java a new String variable to hold the user ID was added, this will be stored  on the json file to verify whether an account is new or not

On DbxOAuthHandler.java on line 79 cred.name, what gets displays on the front end now displays "Dropbox: " following the email associated with the account.  This is for in the event a user wants to use more than one Dropbox account.  The userID is also fetched from the dropbox API and assigned it to the userID.

**Comment by sraviku2** [comment]
Code review completed by Dhruva. Assigned to Yifu for testing.

**Comment by yinyifu** [comment]
Tested and It works, Shows user's email after dropbox:/ and does not contain duplicates. Only time it did not work is when server hang from Logging problem and when dropbox fails with ConcurrentModificationException. But those are not problems directly related to Saving Credential. Good job.

**Comment by jafalca** [comment]
Issue fixed, doesn't delete duplicates anymore; instead it just won't add them if it's a duplicate.
