### ISSUE TITLE
Login to any protocol automatically goes into saved credentials.

### ISSUE THREAD

**Issue by vanditaruldas** [didclab/onedatashare#16]
Whenever the user logins into any of the servers, the login details are automatically saved and are shown in the saved credentials list. This should not be the case. There should be a check box called save credentials and if that is ticked only then should the details be saved.

**Comment by sraviku2** [comment]
This happens only with dropbox, no credentials are saved for FTP/SFTP. The current plan is to remove all credential storing eventually.
