### ISSUE TITLE
No such File or Directory in Google drive on first time connection

### ISSUE THREAD

**Issue by aashish-jain** [didclab/onedatashare#21]
Google drive sometimes displays no such file or directory when re-logged in.

**Comment by aashish-jain** [comment]
![Screenshot from 2019-02-18 22-46-37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c65915d9f229a0012722253/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f3793dd4bb68ed10365559424dab53444d04bea6d37ef5f22e7a985959bcd264097dce3917afb98b1dbf01b8758948d0e5b98a5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5df64ee54555a5163162e0647b.png)

@atulsam and I found that If the oauth token isn't being used, it expires. By default the timeout is 1 hour.

**Comment by atulsam** [comment]
So it is not the problem with the code. If the user is active on the website then it will be no issue and when user login to the website then before using Google Drive we need to renew the token.

**Comment by atulsam** [comment]
Fixed it by using the Refresh Token. Cheers!!!
