### ISSUE TITLE
Dropbox: Listing of folder contents not working and  Transfer not working

### ISSUE THREAD

**Issue by jhuang42** [didclab/onedatashare#25]
DropBox List and Transfer is not working.

**Comment by DhruvaKumarS** [comment]
Both issues fixed. File attached. 
[DbxResource.java.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59779ee9f64d69001ad6409a/125516c66e82c728ace21e0d46cc9682118790a69afbbc46ea57f18228046b313916ac217586f76ae5002e5859564af810590940aaab882da6b63e26db5a59ea84644d68d47f40f2ecdd42e64bef62994597b4bd804dc5e9392ce58f884f381a071b9bb2.txt)
