### ISSUE TITLE
File overwrite

### ISSUE THREAD

**Issue by asif33** [didclab/onedatashare#36]
Ask by pop up that file already exists needs to be added. [Dhruva]

Not able to cancel transfers [Re-direct] [Siddharth]

Monitoring: progress bar should show percentage of progress [Rohit]

History of the transfer should be shown.

Login to admin interface: View transfer histories of all users sorted by id, chronology, file speed, completion time, etc. [Asif]

Write down log files into a text file. [Asif]

**Comment by sraviku2** [comment]
Task completed by Dhruva Kumar and assigned to Jimmy Huang for code review.

**Comment by sraviku2** [comment]
Code review done by Jimmy, assigned to Javier for testing.

**Comment by jafalca** [comment]
Code tested on prod branch

Everything is in order,   the user is told the files that will be overwritten, works for single files as well as multiple both ways.  Perhaps this feature should be on by default
