### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by sraviku2** [didclab/onedatashare#49]

**Comment by sraviku2** [comment]
Completed by Yifu Yin and assigned to Javier for code review.

**Comment by sraviku2** [comment]
Code review completed by Javier. Assigned to Flo for independent testing.

**Comment by ffilsaime** [comment]
Everything seems to be fine. Just one minor thing. When I select two items to drag and drop, I will not know if was successful until the pop box appears.  Here's what I mean. For example, in windows, when I select multiple files the temporary icon i am dragging tells me how many files i am moving. While in the dropbox, temporary icons makes it seem like i am only moving one file. But on the bright side, the multiple files are still moved.
![drag and drop.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b2289b4aa848f0012aa698a/125516c66e82c728ace21e0d46ec869b24c282a78ba9bb51ab4db2d86b56357c2301a03f32dfa17de61422550b0e4ffa450e0d45faf98929f0e73a228d0902ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98845c4ea3b20e48e86483e0c48.png)
![windows example of drag and drop.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b2289b4aa848f0012aa698a/125516c66e82c728ace21e0d46ff9d94278d94bacfeca742a94dfc91694921332d16a22c3084ed2cff46690e1f4d52be011a001ea9aacd39aca439798c550fb9806c0970906f10aab8821de950bc728c1a8ca4a0980e91b6697abad2c51a7c0c0f0a88f85734a59b42cc5af04ee24b55a417242e.png)

**Comment by yinyifu** [comment]
Ok!

**Comment by yinyifu** [comment]
Hi Flo, I have updated the drag n drop so now it gives more feedback about where the files are going. And also it will expand the folder when you long hover it on top of the folder.  Please test it again in my branch if you would like to. For displaying how many files in the selection under the mouse, it is difficult for me right now and result in minor impact, Siddharth and I think it is an enhancement that can go to another ticket. 
Thanks for testing my work.

**Comment by ffilsaime** [comment]
I checked it. I think everything looks fine.
