### ISSUE TITLE
Error on click dropbox

### ISSUE THREAD

**Issue by vanditaruldas** [didclab/onedatashare#5]
One clicking the Dropbox option in the transfer page, the following error comes but does not stop the functionality. Still needs to be fixed.  POST http://127.0.0.1:8080/api/stork/ls 500 (Internal Server Error)(anonymous function)

**Comment by DhruvaKumarS** [comment]
There was an unnecessary ls call to the back-end before a Dropbox account has been authenticated. This has been handled in the front-end and an ls call to the back-end is made only if a Dropbox session has been authenticated.
