### ISSUE TITLE
Implement IsAdmin functionality

### ISSUE THREAD

**Issue by LinusCastelino** [didclab/onedatashare#50]
Currently the IsAdmin functionality just returns true by default.
Implement the isAdmin functionality that only returns true only if the user has the admin flag set on his/her account.

**Comment by aashish-jain** [comment]
The admin functionality has already been implemented. I think there is some issue in the front-end.

**Comment by LinusCastelino** [comment]
Will look into the feasibility of a quickfix.

**Comment by yinyifu** [comment]
implemented #59
