### ISSUE TITLE
Insert transfer job data in mongo

### ISSUE THREAD

**Issue by sraviku2** [didclab/onedatashare#52]

**Comment by sraviku2** [comment]
Task about to be completed by Shreya on 6/14. Code review task assigned to Asif.

**Comment by shreyahegde94** [comment]
Task completed.

The function StorkMessages in class MethodLogs takes the object of class Dump State Thread and parses it as a JSON to get information such as source, destination and so on. [Fields same as the tab queue in one data share application]

This information is added to the jobInformation collection of the database.
