### ISSUE TITLE
Dropbox new credential authentication redirects to error page

### ISSUE THREAD

**Issue by sid-ravikumar** [didclab/onedatashare#6]
The credential gets stored, but the authentication tab loads an error page instead of closing and triggering the transfer page to list files in the dropbox root folder.

**Comment by yinyifu** [comment]
Currently redirecting to Transfer page. Does not log in to endpoint by itself.
Should Login to endpoint by itself.

**Comment by yinyifu** [comment]
Error if the user currently logs in to Dropbox and credential is duplicated.
