### ISSUE TITLE
Include additional fields in registration page

### ISSUE THREAD

**Issue by LinusCastelino** [didclab/onedatashare#63]
Add fields to record user first name, last name and organization.
Organization field should be optional.

**Comment by KiranPrabhakar135** [comment]
Created pull request 
https://github.com/didclab/onedatashare-spring/pull/71

**Comment by KiranPrabhakar135** [comment]
Created Pull request #72 (https://github.com/didclab/onedatashare-spring/pull/72)
Merged changes to master.
