### ISSUE TITLE
Verification hashcode on frontend

### ISSUE THREAD

**Issue by LinusCastelino** [didclab/onedatashare#89]
User starts registration, enters the verification code received via email, clicks on back button.

The complete verification hashcode is displayed to the user.
Should be blank when the user goes back, or should hold the previous value entered.

**Comment by KiranPrabhakar135** [comment]
Included in pull request (#96)

**Comment by KiranPrabhakar135** [comment]
Included other bug fix for using token multiple times with in 24 hours.
Final merge is done as part of pull request(#108)
